version: "3"
services:
  si_180152_rabbit:
    image: rabbitmq:3-alpine
  si_180152_app:
    image: si_180152_app_dotnet
    ports:
      - "18015:80"
    restart: on-failure
    depends_on:
      - si_180152_rabbit
  si_180152_generator:
    image: si_180152_app_generator
    restart: on-failure
    depends_on:
      - si_180152_rabbit