version: "3"
services:
  rabbit:
    image: rabbitmq:3-alpine
    networks:
      - main
  app:
    image: unf0rgiv33n/si_180152_app_dotnet
    networks:
      - main
    ports:
      - "18015:80"
    restart: on-failure
    depends_on:
      - si_180152_rabbit
  generator:
    image: unf0rgiv33n/si_180152_app_generator
    networks:
      - main
    restart: on-failure
    depends_on:
      - si_180152_rabbit

networks:
  main:
    driver: overlay