version: "3"
services:
  rabbit:
    image: rabbitmq:3-alpine
    networks:
      - main
  app:
    #build: ./DotNet/DotNet
    image: unf0rgiv33n/si_180152_app_dotnet
    networks:
      - main
    ports:
      - "18015:80"
    restart: on-failure
    depends_on:
      - rabbit
  front:
    #build: ./front_app
    image: unf0rgiv33n/si_180152_app_front
    networks:
      - main
    ports:
      - "8080:8080"
    restart: on-failure
    depends_on:
      - rabbit
  generator:
    #build: ./generator
    image: unf0rgiv33n/si_180152_app_generator
    networks:
      - main
    restart: on-failure
    depends_on:
      - rabbit
#  mongo:
#    image: mongo
#    restart: always
#    environment:
#      MONGO_INITDB_ROOT_USERNAME: root
#      MONGO_INITDB_ROOT_PASSWORD: example
#  mongo-express:
#    image: mongo-express
#    restart: always
#    ports:
#      - 8081:8081
#    environment:
#      ME_CONFIG_MONGODB_ADMINUSERNAME: root
#      ME_CONFIG_MONGODB_ADMINPASSWORD: example
#      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017

networks:
  main:
    driver: overlay